config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_validation { self.email = email.downcase }
  validates :username, presence: true,
              uniqueness: { case_sensitive: false },
              length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
              uniqueness: true,
              format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i( edit update show destroy )
  before_action :require_user, except: %i( index show )
  before_action :require_same_user, only: %i( edit update destroy )

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article created!"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article trashed"
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description,:user_id, category_ids: [] )
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i( index show )
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category updated"
      redirect_to category_path(@category)
    else
      render "edit"
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category created!"
      redirect_to categories_path
    else
      render "new"
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      if !logged_in? || (logged_in? && !current_user.admin?)
        flash[:danger] = "Only admins can perform that action"
        redirect_to categories_path
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i( edit update show)
  before_action :require_same_user, only: %i( edit update destroy )
  before_action :require_admin, only: %i( destroy )

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the das412 Alpha Blog, #{@user.username}!"
      redirect_to user_path(@user)
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:danger] = "You can only edit your own account"
        redirect_to users_path
      end
    end

    def require_admin
      if logged_in? && !current_user.admin?
        flash[:danger] = "Only admin users can perform that action"
        redirect_to root_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user,options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
  end

end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-8 offset-2" style="padding: 15px;">
      <div class="card card-lg" style="background: rgba(205,205,205,0.5); padding: 15px;">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>
              Created by: <%= article.user.username if article.user %>,
                <%= time_ago_in_words(article.created_at) %> ago, last updated:
                <%= time_ago_in_words(article.updated_at) %>
            </small>
          </div>
        </div>
        <% if article.categories.any? %>
          <p><%= render article.categories %></p>
        <% end %>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit article", edit_article_path(article), class: "btn btn-sm btn-primary" %>
            <%= link_to "Delete this Article", article_path(article), method: :delete,
                                                data: { confirm: "Are you sure?" },
                                                class: "btn btn-sm btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<div class="row">
  <div class="col-sm-12">
    <%= form_for(@article, html: {class:"form-horizonal", role: "form"}) do |f| %>
      <div class="row form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
        </div>
      </div>
      <div class="row form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, class: "form-control", placeholder: "Article Body", rows: 10 %>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-8 offset-2 center">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <%- cb.label(class: "checkbox-inline input_checkbox",style: "padding: 0 5px;") {cb.check_box(class: "checkbox") + cb.text} -%>
            <% end %>
          </div>
        </div>
      </div>

      <div class="row form-group">
        <div class="offset-sm-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>

    <% end %>

    <div class="center col-12 sm-offset-2">
      [ <%= link_to "Cancel Request and Return to Articles Listing", articles_path %> ]
      <%#= link_to "Back to articles listing", articles_path %>
    </div>

  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1 align="center">Listing All Articles</h1>
<div class="row">
  <div class="digg_pagination col-4 offset-4" style="margin-top: 30px; margin-bottom: 30px; padding-left: 60px;">
    <%= will_paginate %>
  </div>
</div>
<%= render "article", obj: @articles %>
<div class="row">
  <div class="digg_pagination col-4 offset-4" style="margin-top: 30px; margin-bottom: 30px; padding-left: 60px;">
    <%= will_paginate %>
  </div>
</div>

app/views/articles/new.html.erb
<h1 align="center"> Create an article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h2 align="center">
  Title: <%= @article.title %>
</h2>

<div class="card col-8 offset-2" style="background: rgba(205,205,205,0.5); padding: 15px;">
  <% if @article.user %>
    <ul class="listing">
      <div class="row center">
        <div class="col-sm-12">
          <li>
            Created by:
          </li>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
          <li><small>
            <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
          </small></li>
        </div>
      </div>
    </ul>
  <% end %>

  <h4 class="center description"><strong>Description:</strong></h4>
  <hr />
  <%= simple_format(@article.description) %>

  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>

  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit article", edit_article_path(@article), class: "btn btn-sm btn-primary" %>
      <%= link_to "Delete this Article", article_path(@article), method: :delete,
                                          data: { confirm: "Are you sure?" },
                                          class: "btn btn-sm btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-sm btn-success" %>
  </div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category), class: "whitelink", style: "padding: 0 2.5px;" %></span>

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category %>

<%= form_for(@category, html: {class:"form-horizonal", role: "form"}) do |f| %>
  <div class="row form-group">
    <div class="control-label col-sm-2">
      <%= f.label :name %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
    </div>
  </div>

  <div class="row form-group">
    <div class="offset-sm-2 col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>

<% end %>

<div class="center col-12 sm-offset-2">
  [ <%= link_to "Cancel Request and Return to Articles Listing", articles_path %> ]
  <%#= link_to "Back to articles listing", articles_path %>
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit category</h1>
<%= render "form" %>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>
<div class="digg_pagination col-4 offset-4" style="margin-top: 30px; margin-bottom: 30px; padding-left: 65px;">
  <%= will_paginate %>
</div>
<div align="center">
  <% @categories.each do |cat| %>
  <ul class="listing">
    <div class="row">
      <div class="card col-4 offset-4" style="background: rgba(205,205,205,0.5); padding: 15px;">
        <li class="article-title">
          <%= link_to "#{cat.name}", category_path(cat) %>
        </li>
        <li><small><%= pluralize(cat.articles.count, "article") %></small></li>
      </div>
    </div>
  </ul>
  <% end %>
</div>
<div class="digg_pagination col-4 offset-4" style="margin-top: 30px; margin-bottom: 30px; padding-left: 65px;">
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>
<%= render "form" %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="center">
    <span class="badge"><%= link_to "Edit Category", edit_category_path(@category), class: "whitelink" %></span>
  </div>
<% end %>

<div class="row center">
  <div class="digg_pagination col-4 offset-4" style="margin-top: 30px; margin-bottom: 30px; padding-left: 60px;">
    <%= will_paginate @category_articles %>
  </div>
</div>
<%= render "articles/article", obj: @category_articles %>
<div class="row">
  <div class="digg_pagination col-4 offset-4" style="margin-top: 30px; margin-bottom: 30px; padding-left: 60px;">
    <%= will_paginate @category_articles %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="https://www.udemy.com">The Complete Ruby on Rails Developer</a> by <a href="http://www.mashrurhossain.com/">Mashrur Hossain</a>
    </small>
    <nav>
      <ul>
        <li>
          <%= link_to "About", about_path %>
        </li>
      </ul>
    </nav>
  </footer>
</div>
  

app/views/layouts/_messages.html.erb
  <div class="col-sm-10 offset-1">
    <% flash.each do |name,msg| %>
      <div class='alert alert-<%="#{name}"%>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="right navbar-nav mr-auto">
      <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-4" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> -->
    </ul>
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <li class="nav-item"><%= link_to "All Articles", articles_path, class: "dropdown-item" %></li>
            <li class="nav-item"><%= link_to "New Article", new_article_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <li class="nav-item"><%= link_to "All Categories", categories_path, class: "dropdown-item" %></li>
            <% Category.all.each do |cat| %>
              <li class="nav-item"><%= link_to "#{cat.name}", category_path(cat), class: "dropdown-item" %></li>
            <% end %>
            <% if logged_in? && current_user.admin? %>
              <div class='dropdown-divider'><%# DIVIDER %></div>
              <li><%= link_to "Create New Category", new_category_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Your Profile <%= "Admin" if current_user.admin? %>
          </a>
          <ul class="dropdown-menu">
            <li class="nav-item"><%= link_to "Edit your profile", edit_user_path(current_user), class:"dropdown-item" %></li>
            <li class="nav-item"><%= link_to "View your profile", user_path(current_user), class:"dropdown-item" %></li>
          </ul>
        </li>

        <li class="nav-item"><%= link_to "All Users", users_path, class: "nav-link"  %></li>

        <li class="nav-item"><%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %></li>

      <% else %>
        <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Sign up", signup_path, class: "nav-link" %></li>
      <% end %>
    </ul>



  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans%7CRoboto:400,500%7CSource+Sans+Pro:300,600' rel='stylesheet'>

  </head>

  <body style=''>

    <%= render "layouts/navigation" %>

    <%= render "layouts/messages" %>

    <div class="container" style="padding: 30px;">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
    <div>
      <%= debug(params) if Rails.env.development? %>

    </div>
  </body>


</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>
<%= link_to 'Home', root_path, style: 'margin: 15px; padding: 8px 30px; font-size: 1.6em;' %>

app/views/pages/home.html.erb
<!--<div style='text-align: center;'>
  <%#= link_to image_tag('home.jpg'), 'www.example.com', style: 'width: 50%;' %>
</div>-->

<style>
  .btn-xlarge { font-size: 1.7em; background-color: #000; margin: 15px; padding: 8px 30px; }
</style>

<div class="center jumbotron">
  <h1 class="heavy display-4">ALPHA BLOG</h1>
  <%= link_to "Sign-up now!", signup_path, class: "btn btn-danger btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row" style="margin-bottom: 15px; color: #c00;">
    <div class="col-8 offset-2">
      <div class="card" style="background: rgba(205,0,0,0.2); margin: 15px; padding: 15px;">
        <div class="card-heading">
          <h3 class="card-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h3>
          <div class="card-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>

<div class="row">
  <div class="col-sm-12">
    <%= form_for(@user, html: {class:"form-horizonal", role: "form"}) do |f| %>
      <div class="row form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter Username", autofocus: true %>
        </div>
      </div>
      <div class="row form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>
      <div class="row form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>

      <div class="row form-group">
        <div class="offset-sm-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update your account", class: "btn btn-primary btn-lg") %>
        </div>
      </div>

    <% end %>

    <div class="center col-12 sm-offset-2">
      [ <%= link_to "Cancel Request and Return to Articles Listing", articles_path %> ]
      <%#= link_to "Back to articles listing", articles_path %>
    </div>

  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>
<div align="center">
  <div class="row">
    <div class="digg_pagination col-4 offset-4" style="margin-top: 30px; margin-bottom: 30px; padding-left: 65px;">
      <%= will_paginate @users %>
    </div>
  </div>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="card col-sm-4 sm-offset-4" style="padding: 15px 0 10px 0;">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article-title"><%= link_to user.username, user_path(user) %></li>
        <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
        <% if logged_in? && current_user.admin? %>
          <li>
            <%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete this user and all of their articles?"} %>
          </li>
        <% end %>
      </div>
    </ul>
  <% end %>
</div>
<div class="row">
  <div class="digg_pagination col-4 offset-4" style="margin-top: 30px; margin-bottom: 30px; padding-left: 65px;">
    <%= will_paginate @users %>
  </div>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign up for das412 Alpha-Blog</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="row">
  <div class="col-4 offset-4 center">
    <%= gravatar_for(@user, size: 150) %>
  </div>
</div>

<h4 align="center"><%= @user.username %>'s Articles</h4>

<div class="row">
  <div class="digg_pagination col-4 offset-4" style="margin-top: 30px; margin-bottom: 30px; padding-left: 60px;">
    <%= will_paginate @user_articles %>
  </div>
</div>

<%= render "articles/article", obj: @user.articles %>

<div class="digg_pagination col-4 offset-4" style="margin-top: 30px; margin-bottom: 30px; padding-left: 60px;">
  <%= will_paginate @user_articles %>
</div>